# Generated by Django 6.0 on 2026-05-03 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_connections', '0002_encrypt_connection_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', 'Manual (API)'), ('scheduled', 'Scheduled job')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=16)),
                ('engine', models.CharField(max_length=32)),
                ('relative_media_path', models.CharField(blank=True, default='', help_text='Path relative to MEDIA_ROOT (POSIX slashes).', max_length=512)),
                ('download_filename', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_records', to='db_connections.databaseconnection')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_records_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=16)),
                ('engine', models.CharField(max_length=32)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_logs', to='backups.backuprecord')),
                ('connection', models.ForeignKey(help_text='Target connection at restore time (same row as backup.connection).', on_delete=django.db.models.deletion.CASCADE, related_name='restore_records', to='db_connections.databaseconnection')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_records_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['connection', '-created_at'], name='backups_bac_connect_0035ea_idx'),
        ),
        migrations.AddIndex(
            model_name='restorerecord',
            index=models.Index(fields=['backup', '-created_at'], name='backups_res_backup__432ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='restorerecord',
            index=models.Index(fields=['connection', '-created_at'], name='backups_res_connect_c6b5b0_idx'),
        ),
    ]
