# Generated by Django 6.0 on 2026-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=16)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='backups_bac_schedul_9fa43d_idx',
            old_name='backups_bac_schedul_6f2a1c_idx',
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='storage_uploads',
            field=models.JSONField(blank=True, default=list, help_text='Per-destination upload results (id, name, kind, ok, relative, remote/error).'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['-created_at', 'status'], name='backups_ale_created_idx'),
        ),
    ]
