# Generated by Django 6.0 on 2026-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Manage users and scheduler jobs via API (with superuser).'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_editor',
            field=models.BooleanField(default=False, help_text='Create/update access when enforced by API permissions.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_viewer',
            field=models.BooleanField(default=False, help_text='Read-oriented access when enforced by API permissions.'),
        ),
    ]
