# Generated by Django 6.0 on 2026-05-03 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_kind', models.CharField(choices=[('interval', 'Every N seconds'), ('crontab', 'Cron expression')], default='interval', max_length=16)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text='Used when schedule kind is interval (minimum 60).', null=True)),
                ('crontab_expression', models.CharField(blank=True, default='', help_text='Five-part cron, e.g. "15 */6 * * *" (minute hour dom month dow).', max_length=128)),
                ('task_key', models.CharField(choices=[('noop', 'No-op (log only)'), ('backup_saved_connection', 'Backup one saved DB connection')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Keyword arguments passed to the task (must be JSON-serializable).')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('', '—'), ('success', 'Success'), ('failed', 'Failed')], default='', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_as', models.ForeignKey(blank=True, help_text='Required for backup_saved_connection (scopes DB rows to this user).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'next_run'], name='scheduler_s_enabled_78aa12_idx')],
            },
        ),
    ]
