# Generated by Django 6.0 on 2026-05-03 14:27

import db_connections.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique label per user.', max_length=255)),
                ('kind', models.CharField(choices=[('s3', 'S3 / compatible'), ('sftp', 'SFTP'), ('ftp', 'FTP')], max_length=16)),
                ('host', models.CharField(blank=True, default='', help_text='SFTP/FTP hostname.', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, help_text='Defaults: SFTP 22, FTP 21 when left empty.', null=True)),
                ('username', models.CharField(blank=True, default='', help_text='S3 access key ID or SSH/FTP user.', max_length=255)),
                ('secret', db_connections.fields.EncryptedTextField(blank=True, default='', help_text='S3 secret key or SFTP/FTP password (encrypted at rest).')),
                ('bucket', models.CharField(blank=True, default='', help_text='S3 bucket name.', max_length=255)),
                ('region', models.CharField(blank=True, default='', help_text='Optional AWS region.', max_length=64)),
                ('endpoint_url', models.CharField(blank=True, default='', help_text='Custom S3 endpoint (e.g. MinIO). Leave blank for default AWS.', max_length=500)),
                ('remote_path', models.CharField(blank=True, default='', help_text='Remote directory prefix for SFTP/FTP uploads.', max_length=512)),
                ('ftp_passive', models.BooleanField(default=True)),
                ('ftp_use_tls', models.BooleanField(default=False, help_text='FTP over TLS (FTPS).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='storage_dest_unique_name_per_user')],
            },
        ),
    ]
