# Generated by Django 6.0 on 2026-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedestination',
            name='remote_path',
            field=models.CharField(blank=True, default='', help_text='Directory or object-key prefix for uploads (S3/SFTP/FTP).', max_length=512),
        ),
    ]
