# Generated by Django 6.0 on 2026-05-03 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label shown in your list (unique per user).', max_length=255)),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('postgresql', 'PostgreSQL'), ('redis', 'Redis'), ('rabbitmq', 'RabbitMQ'), ('clickhouse', 'ClickHouse'), ('sqlserver', 'Microsoft SQL Server'), ('mongodb', 'MongoDB')], max_length=32)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, help_text='Leave empty to use the default port for this engine on the client.', null=True)),
                ('database_name', models.CharField(blank=True, help_text='Database/schema/bucket name where applicable. For Redis: logical DB index (e.g. 0).', max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.TextField(blank=True)),
                ('virtual_host', models.CharField(blank=True, default='', help_text='RabbitMQ vhost (often /).', max_length=255)),
                ('connection_uri', models.TextField(blank=True, help_text='Optional full connection URI (common for MongoDB; can be extended for others).')),
                ('use_tls', models.BooleanField(default=False, help_text='TLS/SSL for the connection where the driver supports it.')),
                ('extra_options', models.JSONField(blank=True, default=dict, help_text='Engine-specific options (e.g. SQL Server ODBC driver name, Mongo authSource).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='db_connections_unique_name_per_user')],
            },
        ),
    ]
