# Generated by Django 6.0 on 2026-05-03 12:24

import db_connections.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=db_connections.fields.EncryptedTextField(blank=True, help_text='Stored encrypted at rest. Prefer setting DB_CREDENTIALS_FERNET_KEY in production.'),
        ),
    ]
