# Generated by Django 6.0 on 2026-09-20 08:33

import db_connections.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_connections', '0003_database_connections_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_enabled',
            field=models.BooleanField(default=False, help_text='Open an SSH local port-forward before backup/test/restore.'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_host',
            field=models.CharField(blank=True, default='', help_text='SSH bastion / server hostname (public address).', max_length=255),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_host_key_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Required when SSH is enabled. SHA256 fingerprint of the server host key (from: ssh-keyscan HOST | ssh-keygen -lf -).', max_length=128),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_password',
            field=db_connections.fields.EncryptedTextField(blank=True, default='', help_text='SSH password (optional if a private key is set). Encrypted at rest.'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_port',
            field=models.PositiveIntegerField(blank=True, default=22, help_text='SSH port (default 22).', null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_private_key',
            field=db_connections.fields.EncryptedTextField(blank=True, default='', help_text='PEM private key for SSH (preferred). Encrypted at rest.'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_private_key_passphrase',
            field=db_connections.fields.EncryptedTextField(blank=True, default='', help_text='Passphrase for the SSH private key, if any. Encrypted at rest.'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(blank=True, help_text='Database host. With SSH tunnel enabled, this is the address as seen from the SSH server (often 127.0.0.1).', max_length=255),
        ),
    ]
